# Generated by Django 6.0.4 on 2026-05-03 10:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(choices=[('twitch', 'Twitch')], help_text='Host name', max_length=16)),
                ('host_user_id', models.CharField(help_text='User ID defined by host', max_length=64)),
                ('host_login', models.CharField(help_text='User login defined by host', max_length=64)),
                ('host_display_name', models.CharField(help_text='User display name defined by host', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time of the latest update for the profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('host', 'host_user_id'), name='unique_host_user')],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('live', 'Live'), ('offline', 'Offline')], default='live', help_text='Whether the stream is currently live or offline - defined by host', max_length=16)),
                ('host_stream_id', models.CharField(help_text='An ID that identifies the stream - defined by host', max_length=64)),
                ('language', models.CharField(help_text='ISO 639-1 two-letter language code', max_length=2)),
                ('host_game_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='The game IDs detected by snapshots')),
                ('max_viewers', models.PositiveIntegerField(default=0, help_text='Max viewers number detected by snapshots')),
                ('avg_viewers', models.PositiveIntegerField(default=0, help_text='Average viewers number calculated via snapshots')),
                ('started_at', models.DateTimeField(help_text='Time when stream started - defined by host')),
                ('finished_at', models.DateTimeField(help_text='Time when stream finished. While the stream is live, this is updated on every poll to act as last seen alive. Once the stream goes offline, the value is finalized and stops updating.')),
                ('streamer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='streams.streamerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StreamSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewers', models.PositiveIntegerField(help_text='Current number of viewers')),
                ('shot_at', models.DateTimeField(auto_now_add=True, help_text='Time at which the snapshot was made')),
                ('host_game_id', models.CharField(help_text='The game ID currently being streamed - defined by host', max_length=64)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='streams.stream')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('streamer_profile', 'host_stream_id'), name='unique_host_stream'),
        ),
    ]
