# Generated by Django 6.0.4 on 2026-05-04 08:35

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(choices=[('twitch', 'Twitch')], help_text='Host name', max_length=16)),
                ('host_user_id', models.BigIntegerField(help_text='User ID defined by host')),
                ('host_login', models.CharField(help_text='User login defined by host', max_length=64)),
                ('host_display_name', models.CharField(help_text='User display name defined by host', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time of the latest update for the profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('host', 'host_user_id'), name='unique_host_user')],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('live', 'Live'), ('offline', 'Offline')], default='live', help_text='Whether the stream is currently live or offline - defined by host', max_length=16)),
                ('host_stream_id', models.BigIntegerField(help_text='An ID that identifies the stream - defined by host')),
                ('language', models.CharField(help_text='ISO 639-1 two-letter language code', max_length=2)),
                ('max_viewers', models.PositiveIntegerField(db_index=True, default=0, help_text='Max viewers observed across all snapshots. Populated when the stream goes offline; live streams stay at 0.')),
                ('started_at', models.DateTimeField(help_text='Time when stream started - defined by host')),
                ('finished_at', models.DateTimeField(help_text='Time when stream finished. While the stream is live, this is updated on every poll to act as last seen alive. Once the stream goes offline, the value is finalized and stops updating.')),
                ('snapshots', models.JSONField(blank=True, default=list, help_text='Rolling list of per-poll observations appended while the stream is live. Each entry is a dict with short keys: g=host_game_id, v=viewers, t=poll_timestamp_unix.')),
                ('host_game_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, help_text='Distinct game IDs observed across snapshots. Populated when the stream goes offline; supports fast lookup by game.')),
                ('streamer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='streams.streamerprofile')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['host_game_ids'], name='stream_host_game_ids_gin')],
                'constraints': [models.UniqueConstraint(fields=('streamer_profile', 'host_stream_id'), name='unique_host_stream')],
            },
        ),
    ]
