# Generated by Django 6.0.4 on 2026-05-03 22:55

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='host_game_ids',
        ),
        migrations.AddField(
            model_name='stream',
            name='game_metrics',
            field=models.JSONField(blank=True, default=list, help_text='Per-game metrics aggregated from snapshots once the stream goes offline. List of dicts with short keys to keep JSONB compact: g=host_game_id, mv=max_viewers, av=avg_viewers, d=duration_seconds.'),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=django.contrib.postgres.indexes.GinIndex(fields=['game_metrics'], name='stream_game_metrics_gin'),
        ),
    ]
