# Generated by Django 6.0.4 on 2026-05-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_genre_id', models.BigIntegerField(help_text='An ID that identifies the game genre - defined by host; set once at time of creation; used as unique identifier for mapping data from IGDB API response.', unique=True)),
                ('host_name', models.CharField(help_text='Genre readable name - defined by host; updated on every pull if mismatched.', max_length=64)),
                ('host_url', models.CharField(help_text='Source URL to the dedicated page of the genre - defined by host.', max_length=1024)),
                ('slug', models.CharField(help_text='Genre slug - defined by host; set once at time of creation; later use for internal URLs.', max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_game_id', models.BigIntegerField(help_text='An ID that identifies the game - defined by host; set once at time of creation; used as unique identifier for mapping data from IGDB API response.', unique=True)),
                ('host_name', models.CharField(blank=True, default='', help_text='Game readable name - defined by host. Empty until enriched from IGDB.', max_length=255)),
                ('host_summary', models.TextField(blank=True, default='', help_text='Game description - defined by host. Empty until enriched from IGDB.')),
                ('host_url', models.CharField(blank=True, default='', help_text='Source URL to the dedicated page of the game - defined by host. Empty until enriched from IGDB.', max_length=1024)),
                ('genres', models.ManyToManyField(blank=True, related_name='games', to='streams.gamegenre')),
            ],
        ),
    ]
