# Generated by Django 6.0.4 on 2026-05-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_gamegenre_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('new', 'New'), ('isgame', 'Is Game'), ('isnongame', 'Is non-Game')], default='new', help_text="Current status of the game entry. 'New' on insertion, and either 'Is Game' or 'Is non-Game' on data enrichment.", max_length=16),
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_game_id',
            field=models.BigIntegerField(blank=True, default=0, help_text="An unique identifier for mapping data from IGDB API response - defined by Helix API response. Empty until updated during game data enrichment from Helix API (the 'get games' endpoint) - empty if not exists."),
        ),
        migrations.AlterField(
            model_name='game',
            name='host_game_id',
            field=models.BigIntegerField(help_text="An unique identifier for mapping data from Helix API response - defined by Helix API response. Set once at time of creation (the 'get streams' endpoint).", unique=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('offline', 'Offline'), ('approved', 'Approved')], default='live', help_text='Whether the stream is currently live or offline - defined by host', max_length=16),
        ),
    ]
